env:
  JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
  SECRET_KEY: ${SECRET_KEY}
spring:
  application:
    name: meaudote
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl